//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GooCooAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GooCooAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 300 的本地化字符串。
        /// </summary>
        internal static string INT_AUTHORYLIFETIME {
            get {
                return ResourceManager.GetString("INT_AUTHORYLIFETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GooCoo图书管理系统 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BorrowHandler 的本地化字符串。
        /// </summary>
        internal static string URL_BORROW {
            get {
                return ResourceManager.GetString("URL_BORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DonateHandler 的本地化字符串。
        /// </summary>
        internal static string URL_DONATE {
            get {
                return ResourceManager.GetString("URL_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FindBookHandler 的本地化字符串。
        /// </summary>
        internal static string URL_FINDBOOK {
            get {
                return ResourceManager.GetString("URL_FINDBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FindUserHandler 的本地化字符串。
        /// </summary>
        internal static string URL_FINDUSER {
            get {
                return ResourceManager.GetString("URL_FINDUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetBookByBorrow 的本地化字符串。
        /// </summary>
        internal static string URL_GETBOOKBYBORROW {
            get {
                return ResourceManager.GetString("URL_GETBOOKBYBORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetBookByFavor 的本地化字符串。
        /// </summary>
        internal static string URL_GETBOOKBYFAVOR {
            get {
                return ResourceManager.GetString("URL_GETBOOKBYFAVOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetBookByOrder 的本地化字符串。
        /// </summary>
        internal static string URL_GETBOOKBYORDER {
            get {
                return ResourceManager.GetString("URL_GETBOOKBYORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetUserByBorrow 的本地化字符串。
        /// </summary>
        internal static string URL_GETUSERBYBORROW {
            get {
                return ResourceManager.GetString("URL_GETUSERBYBORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetUserByFavor 的本地化字符串。
        /// </summary>
        internal static string URL_GETUSERBYFAVOR {
            get {
                return ResourceManager.GetString("URL_GETUSERBYFAVOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetUserByOrder 的本地化字符串。
        /// </summary>
        internal static string URL_GETUSERBYORDER {
            get {
                return ResourceManager.GetString("URL_GETUSERBYORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginHandler 的本地化字符串。
        /// </summary>
        internal static string URL_LOGIN {
            get {
                return ResourceManager.GetString("URL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReturnHandler 的本地化字符串。
        /// </summary>
        internal static string URL_RETURN {
            get {
                return ResourceManager.GetString("URL_RETURN", resourceCulture);
            }
        }
    }
}
